export default [
    {
        path: '/debug',
        router: require('./debug')
    }, {
        path: '/account',
        router: require('./account')
    }, {
        path: '/album',
        router: require('./album')
    }, {
        path: '/country',
        router: require('./country')
    }, {
        path: '/post',
        router: require('./post')
    }, {
        path: '/category',
        router: require('./catogory')
    }, {
        path: '/user',
        router: require('./user')
    }, {
        path: '/media',
        router: require('./media')
    }, {
        path: '/tag',
        router: require('./tag')
    }, {
        path: '/place',
        router: require('./place')
    }, {
        path: '/location',
        router: require('./location')
    }, {
        path: '/team',
        router: require('./team')
    }, {
        path: '/history',
        router: require('./history')
    }, {
        path: '/discover',
        router: require('./discover')
    }, {
        path: '/clients',
        router: require('./client')
    }, {
        path: '/oauth2',
        router: require('./oauth2')
    }, {
        path: '/app',
        router: require('./app')
    }, {
        path: '/chat',
        router: require('./chat')
    }, {
        path: '/firebase',
        router: require('./firebase')
    }, {
        path: '/ai',
        router: require('./ai')
    }, {
        path: '/report',
        router: require('./report')
    }, {
        path: '/referral',
        router: require('./referral')
    }, {
        path: '/feeds',
        router: require('./feeds')
    }, {
        path: '/goods-order',
        router: require('./goods_order')
    },{
        path: '/topgroup',
        router: require('./top_group')
    }, {
        path: '/admin',
        router: require('./admin')
    }
];